name: 🐞 bug fix
description: "file a bug in noop services"
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - noop-cloud/noop
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!
  - type: markdown
    attributes:
      value: |
        - Please review open issues labeled as `bugs` to ensure your issue is not a duplicate.
        - For general questions, ideas and concerns that are not related to a bug, visit our [discussions page](https://github.com/noop-cloud/supreme-garbanzo/discussions)
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: affected-os
    attributes:
      label: Operating System
      description: What Operating System(s) have you experienced this bug on?
      multiple: true
      options:
        - Windows
        - MacOS
    validations:
      required: false
  - type: dropdown
    id: affected-arch
    attributes:
      label: Architecture
      description: What machine architecture(s) have you experienced this bug on?
      multiple: true
      options:
        - amd64
        - arm64
    validations:
      required: false
  - type: dropdown
    id: affected-browsers
    attributes:
      label: Affected Browsers
      description: If using the web application, which browsers have you experiened this bug in?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: false
  - type: dropdown
    id: application-variant
    attributes:
      label:  Noop Variant
      description: Which variant(s) of Noop are you experiencing this bug?
      multiple: true
      options:
        - Web
        - Desktop
  - type: dropdown
    id: application-mode
    attributes:
      label:  Noop Mode
      description: Which run time mode(s) of Noop are you experiencing this bug?
      multiple: true
      options:
        - Local Development
        - Cloud Platform
  - type: dropdown
    id: affected-versions
    attributes:
      label:  Noop Version
      description: What version(s) of Noop have you experienced this bug with?
      multiple: true
      options:
        - 0.9.33 (default)
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Please describe the bug with as much details as possible. Feel free to attach screenshots, files or link to public gists for better triaging.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expectation
      description: What did you expect to happen?
      placeholder: Tell us your expectation
      value: "I expected foo but received bar!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy & paste any relevant log output. It will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](./code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true