name:  Feature Request
description: Submit a feature request
title: "[Feature]: "
labels: ["enhancement", "feature", "review"]
assignees:
  - noop-cloud/noop
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: happened
    attributes:
      label: The Feature
      description: Please provide details on what feature or enhancement you would like to see
      placeholder: Tell us how the feature should work
      value: "Allow tasks to be stopped"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Noop Version
      description: What version of our software are you currently running?
      options:
        - 0.9.33 (Default)
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true