name:  🔧 submit a feature request
description: submit a feature request
title: "[Feature]: "
labels: ["enhancement", "feature", "review"]
assignees:
  - noop-cloud/noop
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature
    attributes:
      label: New Feature
      description: A clear and concise description of the feature you would like to see implemented.
      placeholder: Tell us about the feature and how it should work
      value: "Allow an executing task to be stopped"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Value Added
      description: A clear and concise description of what value is added / problem is solved by feature.
      placeholder: Tell us why we need this feature
      value: "I'm always frustrated when [...]"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Noop Version
      description: What version of our software are you currently running?
      options:
        - 0.9.33 (Default)
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](./code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true